#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
picom --experimental-backends &
feh --bg-fill ~/.wallpaper/bg.jpg
~/.config/polybar/launch.sh &
xrdb ~/.Xresources &

bspc monitor -d I II III IV V

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer false

bspc config active_border_color "#aa88cc"
bspc config focused_border_color "#aa88cc"

bspc rule -a code-oss desktop='^1'
bspc rule -a firefox desktop='^2'
bspc rule -a discord desktop='^4'
bspc rule -a mgba state=floating
